name: SkullGetter
version: 0.0.1-SNAPSHOT
description:
author: Hinyari_Gohan
main: com.github.gotochan.SkullGetter
softdepend: [Vault]

commands:
  skullgetter:
    permissions: sg.use
    description: SkullGetterのコマンドです。
    aliases: [sg,skullget,sget]
permissions:
  sg.admin:
    children:
      sg.use: true
    default: op
  sg.use:
    default: true